{
 "title": "All Data Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Sites",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load Average (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Average (5m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load5{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Average (15m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load15{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"$job\"} - node_boot_time_seconds{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Healthy Hosts",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(up{job=\"$job\"}==1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\", job=\"$job\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$job\"}[$__rate_interval])))) * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "RAM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"$job\"} - node_memory_MemFree_bytes{job=\"$job\"}) / (node_memory_MemTotal_bytes{job=\"$job\"} )) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Root FS Used / (%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", job=\"$job\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\", job=\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Disk Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Disk Read Average Wait Time",
   "type": "timeseries",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{job=\"$job\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Disk Write Average Wait Time",
   "type": "timeseries",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_write_time_seconds_total{job=\"$job\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Disk Read IOps Completed",
   "type": "timeseries",
   "description": "The number (after merges) of I/O requests completed per second for the device",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Disk Write IOps Completed",
   "type": "timeseries",
   "description": "The number (after merges) of I/O requests completed per second for the device",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  { "title": "Network Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Network RX (kbps)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"ens3\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Network TX (kbps)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"ens3\", job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  }
 ]
}